ALTER TABLE
    `admin_users` 
ADD `last_name` TEXT NULL DEFAULT NULL,
ADD `company_name` TEXT NULL DEFAULT NULL,
ADD `email` TEXT NULL DEFAULT NULL,
ADD `phone_number` TEXT NULL DEFAULT NULL,
ADD `address` TEXT NULL DEFAULT NULL,
ADD `about` TEXT NULL DEFAULT NULL,
ADD `services` TEXT NULL DEFAULT NULL,
ADD `longitude` TEXT NULL DEFAULT NULL,
ADD `latitude` TEXT NULL DEFAULT NULL,
ADD `division` TEXT NULL DEFAULT NULL,
ADD `opening_hours` TEXT NULL DEFAULT NULL,
ADD `cover_photo` TEXT NULL DEFAULT NULL,
ADD `facebook` TEXT NULL DEFAULT NULL,
ADD `twitter` TEXT NULL DEFAULT NULL,
ADD `whatsapp` TEXT NULL DEFAULT NULL,
ADD `youtube` TEXT NULL DEFAULT NULL,
ADD `instagram` TEXT NULL DEFAULT NULL,
ADD `last_seen` TEXT NULL DEFAULT NULL,
ADD `status` TEXT NULL DEFAULT NULL,
ADD `linkedin` TEXT NULL DEFAULT NULL,
ADD `category_id` TEXT NULL DEFAULT NULL,
ADD `status_comment` TEXT NULL DEFAULT NULL,
ADD `country_id` TEXT NULL DEFAULT NULL,
ADD `region` TEXT NULL DEFAULT NULL,
ADD `district` TEXT NULL DEFAULT NULL,
ADD `sub_county` TEXT NULL DEFAULT NULL;
         
  
  
  